export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ORDERS_REQUEST = "ORDERS_REQUEST";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAIL = "ORDERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";

export const USER_UPDATE_REQUEST_BY_ADMIN = "USER_UPDATE_REQUEST_BY_ADMIN";
export const USER_UPDATE_SUCCESS_BY_ADMIN = "USER_UPDATE_SUCCESS_BY_ADMIN";
export const USER_UPDATE_FAIL_BY_ADMIN = "USER_UPDATE_FAIL_BY_ADMIN";
export const USER_DETAILS_RESET_ADMIN = "USER_DETAILS_RESET_ADMIN";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_DETAILS_UPDATE_REQUEST = "USER_DETAILS_UPDATE_REQUEST";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
export const USER_DETAILS_UPDATE_FAIL = "USER_DETAILS_UPDATE_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCES";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";
export const PAY_ORDER_RESET = "PAY_ORDER_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const ORDERS_RESET = "ORDERS_RESET";
export const RESET_CART = "RESET_CART";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const LOGOUT = "LOGOUT";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";
export const ALL_ORDERS_RESET = "ALL_ORDERS_RESET";

export const SET_DELIVERED_REQUEST = "SET_DELIVERED_REQUEST";
export const SET_DELIVERED_SUCCESS = "SET_DELIVERED_SUCCESS";
export const SET_DELIVERED_FAIL = "SET_DELIVERED_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const POST_REVIEW_REQUEST = "POST_REVIEW_REQUEST";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";
export const POST_REVIEW_RESET = "POST_REVIEW_RESET";

export const TOP_PRODUCTS_REQUEST = "TOP_PRODUCTS_REQUEST";
export const TOP_PRODUCTS_SUCCESS = "TOP_PRODUCTS_SUCCESS";
export const TOP_PRODUCTS_FAIL = "TOP_PRODUCTS_FAIL";
